### ISSUE TITLE
mplayer doesnt quit in middle of a song

### ISSUE THREAD

**Issue by gotbletu** [drakedevel/gsclient#3]
not sure if this is an issue with this app but, how do u stop mplayer in the middle of a song. I do not  want to exit the program (ctrl+c)

i try hitting q to quit, so i can select another song but it doesnt quit.
i have to do a killall mplayer then it exits and gives me the selection prompt again.

mplayer works as it should in my other apps just not with gsclient.

i tryed on 2 machines to be sure. Xubuntu and Archlinux

Thanks i digg the app =D

**Comment by drakedevel** [comment]
Closing since Grooveshark is now defunct
